### ISSUE TITLE
Embed foundationdb fdb_c.h and fdb.options files for docs.rs

### ISSUE THREAD

**Issue by Speedy37** [Clikengo/foundationdb-rs#163]
Currently foundationdb-sys generate options.rs at build time.

We should probable pregenerate options.rs for each platform and fdbclient major version.

**Comment by thoughtpolice** [comment]
Why? Is there any problem with just running the generator? I specifically implemented #97 last year precisely so that these files *do not* need to be generated and committed to the repository, which I saw as a hack. At the time I implemented this, there was only one major version supported, so it required regenerating and overwriting the old code to make it work with v5.2. In practice doing so made it significantly more annoying to build against new FDB features. With the generator, there are still a few patches that are needed to enable new major versions, but due to FDB's design that's always going to be an issue no matter what.

I suppose doing this by committing files for *every version and platform* is possible and makes multi-version support viable, but I'm curious as to why? It seems hackish to commit thousands of lines of code for such a purpose. (I suppose it could slightly improve compile times, but that's probably not going to do much as long as bindgen sits in the dependency tree anyway.) Other language bindings that do this, to my knowledge, only do it due to limitations in the underlying build process, not because it's more robust or preferable. Cargo supports this case well, however.

**Comment by Speedy37** [comment]
There is no issue with the current generation.
The only downside to me are:

 - the clang requirements for building (not important)
 - the stability of option enum names
 - I'm pretty sure docs.rs will fail to build due to foundationdb not being installed (most important).

**Comment by Speedy37** [comment]
So at least we need to embed fdb_c.h and fdb.options

**Comment by Speedy37** [comment]
The main question is: What should be the default? embedded or local install?
