### ISSUE TITLE
Documentation suggests using a method that appears not to exist

### ISSUE THREAD

**Issue by Daniel-B-Smith** [Clikengo/foundationdb-rs#207]
All of the documentation suggests using the `run()` method as the safe alternative. However, it appears that method was removed in https://github.com/Clikengo/foundationdb-rs/commit/c53f7f67411f5a23f65aacd238f428b6ed348474. It's unclear to me what the suggested API is in 0.5.

**Comment by Speedy37** [comment]
In rust, non unsafe methods cannot cause undefined behavior. If found ways to cause UB with the `run` method.
So unfortunately, I had to rollback to the `0.3` / `0.4` way of starting the network thread which now requires an unsafe block.
This is due to the network thread MUST be stopped before the program exits.

I see there is still references to the now removed `run()` methods in the documentation, they should be removed.
